#!/usr/bin/env bash
# Configures a new Ubuntu machine

sudo apt -y update
sudo apt -y install nginx
#ufw allow 'Nginx HTTP'
echo "Ceci n'est pas une page" | sudo tee /var/www/html/404.html


sudo service nginx restart
