#!/usr/bin/env bash
# To infinity and beyond indefinitely
# With sleep 2 between each iteration

while true
do
    echo "To infinity and beyond"
    trap "echo I am invincible!!!" SIGTERM
    sleep 2
done
